# Generated by Django 6.1.2 on 2026-10-09 04:25

from django.db import migrations, models


# Ajusto la clave primaria y conservo las relaciones existentes.
class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0002_auto_20261007_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(db_column='nombre', max_length=50, unique=True),
        ),
    ]
