# Generated by Django 6.1.2 on 2026-10-09 04:15

import django.db.models.deletion
from django.db import migrations, models


# Registro el esquema académico inicial de Sprint 2.
class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0004_alter_docente_especialidad_alter_docente_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id_idioma', models.AutoField(db_column='IdIdioma', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100, unique=True)),
                ('codigo', models.CharField(blank=True, db_column='Codigo', max_length=10, null=True, unique=True)),
                ('activo', models.BooleanField(db_column='Activo', default=True)),
            ],
            options={
                'db_table': 'idioma',
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id_nivel', models.AutoField(db_column='IdNivel', primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_column='Codigo', max_length=20, unique=True)),
            ],
            options={
                'db_table': 'nivel',
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id_programa', models.AutoField(db_column='IdPrograma', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=150)),
                ('duracion_meses', models.IntegerField(blank=True, db_column='DuracionMeses', null=True)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
                ('activo', models.BooleanField(db_column='Activo', default=True)),
            ],
            options={
                'db_table': 'programa',
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id_turno', models.AutoField(db_column='IdTurno', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=50, unique=True)),
                ('hora_referencia_inicio', models.TimeField(blank=True, db_column='HoraReferenciaInicio', null=True)),
                ('hora_referencia_fin', models.TimeField(blank=True, db_column='HoraReferenciaFin', null=True)),
            ],
            options={
                'db_table': 'turno',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(db_column='IdCurso', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=150)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
                ('activo', models.BooleanField(db_column='Activo', default=True)),
                ('idioma', models.ForeignKey(db_column='IdIdioma', on_delete=django.db.models.deletion.PROTECT, related_name='cursos', to='cursos.idioma')),
                ('nivel', models.ForeignKey(db_column='IdNivel', on_delete=django.db.models.deletion.PROTECT, related_name='cursos', to='cursos.nivel')),
            ],
            options={
                'db_table': 'curso',
            },
        ),
        migrations.CreateModel(
            name='Paralelo',
            fields=[
                ('id_paralelo', models.AutoField(db_column='IdParalelo', primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_column='Codigo', max_length=50, unique=True)),
                ('modalidad', models.CharField(blank=True, db_column='Modalidad', max_length=50, null=True)),
                ('aula', models.CharField(blank=True, db_column='Aula', max_length=100, null=True)),
                ('cupo_minimo_apertura', models.IntegerField(blank=True, db_column='CupoMinimoApertura', null=True)),
                ('cupo_maximo', models.IntegerField(blank=True, db_column='CupoMaximo', null=True)),
                ('fecha_inicio', models.DateField(blank=True, db_column='FechaInicio', null=True)),
                ('fecha_fin', models.DateField(blank=True, db_column='FechaFin', null=True)),
                ('estado', models.CharField(db_column='Estado', default='ACTIVO', max_length=30)),
                ('curso', models.ForeignKey(db_column='IdCurso', on_delete=django.db.models.deletion.PROTECT, related_name='paralelos', to='cursos.curso')),
                ('docente', models.ForeignKey(db_column='IdDocente', on_delete=django.db.models.deletion.PROTECT, related_name='paralelos', to='usuarios.docente')),
                ('programa', models.ForeignKey(blank=True, db_column='IdPrograma', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paralelos', to='cursos.programa')),
                ('turno', models.ForeignKey(db_column='IdTurno', on_delete=django.db.models.deletion.PROTECT, related_name='paralelos', to='cursos.turno')),
            ],
            options={
                'db_table': 'paralelo',
            },
        ),
        migrations.CreateModel(
            name='HorarioParalelo',
            fields=[
                ('id_horario', models.AutoField(db_column='IdHorario', primary_key=True, serialize=False)),
                ('dia_semana', models.CharField(db_column='DiaSemana', max_length=20)),
                ('hora_inicio', models.TimeField(db_column='HoraInicio')),
                ('hora_fin', models.TimeField(db_column='HoraFin')),
                ('paralelo', models.ForeignKey(db_column='IdParalelo', on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='cursos.paralelo')),
            ],
            options={
                'db_table': 'horario_paralelo',
            },
        ),
        migrations.CreateModel(
            name='DocenteIdioma',
            fields=[
                ('id_docente_idioma', models.AutoField(db_column='IdDocenteIdioma', primary_key=True, serialize=False)),
                ('docente', models.ForeignKey(db_column='IdDocente', on_delete=django.db.models.deletion.CASCADE, related_name='idiomas_docente', to='usuarios.docente')),
                ('idioma', models.ForeignKey(db_column='IdIdioma', on_delete=django.db.models.deletion.CASCADE, related_name='docentes', to='cursos.idioma')),
            ],
            options={
                'db_table': 'docente_idioma',
                'constraints': [models.UniqueConstraint(fields=('docente', 'idioma'), name='uq_docente_idioma')],
            },
        ),
        migrations.CreateModel(
            name='EstudianteParalelo',
            fields=[
                ('id_estudiante_paralelo', models.AutoField(db_column='IdEstudianteParalelo', primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateField(auto_now_add=True, db_column='FechaIngreso')),
                ('estado', models.CharField(db_column='Estado', default='ACTIVO', max_length=30)),
                ('estudiante', models.ForeignKey(db_column='IdEstudiante', on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='usuarios.estudiante')),
                ('paralelo', models.ForeignKey(db_column='IdParalelo', on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='cursos.paralelo')),
            ],
            options={
                'db_table': 'estudiante_paralelo',
                'constraints': [models.UniqueConstraint(fields=('estudiante', 'paralelo'), name='uq_estudiante_paralelo')],
            },
        ),
        migrations.CreateModel(
            name='ProgramaIdioma',
            fields=[
                ('id_programa_idioma', models.AutoField(db_column='IdProgramaIdioma', primary_key=True, serialize=False)),
                ('idioma', models.ForeignKey(db_column='IdIdioma', on_delete=django.db.models.deletion.PROTECT, related_name='programas', to='cursos.idioma')),
                ('nivel_maximo', models.ForeignKey(db_column='NivelMaximoId', on_delete=django.db.models.deletion.PROTECT, related_name='programas', to='cursos.nivel')),
                ('programa', models.ForeignKey(db_column='IdPrograma', on_delete=django.db.models.deletion.CASCADE, related_name='idiomas', to='cursos.programa')),
            ],
            options={
                'db_table': 'programa_idioma',
                'constraints': [models.UniqueConstraint(fields=('programa', 'idioma'), name='uq_programa_idioma')],
            },
        ),
    ]
