# Generated by Django 6.1.2 on 2026-10-08 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rol', '0002_auto_20261007_2035'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(db_column='IdUsuario', primary_key=True, serialize=False)),
                ('nombres', models.CharField(db_column='Nombres', max_length=100)),
                ('ap_pat', models.CharField(db_column='ApPat', max_length=100)),
                ('ap_mat', models.CharField(db_column='ApMat', max_length=100)),
                ('ci', models.CharField(blank=True, db_column='Ci', max_length=20, null=True, unique=True)),
                ('correo', models.EmailField(db_column='Correo', max_length=150, unique=True)),
                ('password_hash', models.CharField(db_column='PasswordHash', max_length=255)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=30, null=True)),
                ('estado', models.BooleanField(db_column='Estado', default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_column='FechaRegistro')),
                ('rol', models.ForeignKey(db_column='IdRol', on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='rol.rol')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('usuario', models.OneToOneField(db_column='IdUsuario', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='docente', serialize=False, to='usuarios.usuario')),
                ('especialidad', models.CharField(blank=True, db_column='Especialidad', max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'db_table': 'docente',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('usuario', models.OneToOneField(db_column='IdUsuario', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='estudiante', serialize=False, to='usuarios.usuario')),
                ('codigo_estudiante', models.CharField(blank=True, db_column='CodigoEstudiante', max_length=50, null=True, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, db_column='FechaNacimiento', null=True)),
                ('contacto_emergencia', models.CharField(blank=True, db_column='ContactoEmergencia', max_length=150, null=True)),
                ('telefono_emergencia', models.CharField(blank=True, db_column='TelefonoEmergencia', max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'db_table': 'estudiante',
            },
        ),
    ]
