# Generated by Django 6.1.2 on 2026-10-08 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='debe_cambiar_password',
            field=models.BooleanField(db_column='DebeCambiarPassword', default=False),
        ),
    ]
