# Generated by Django 6.1.2 on 2026-10-09 04:25

from django.db import migrations


# Conservo los nombres físicos y mapeos ya existentes en Azure.
class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0003_remove_rol_id_rol_id_rol_alter_rol_nombre'),
        ('usuarios', '0003_usuario_debe_cambiar_password'),
    ]

    operations = []
