# Generated by Django 6.1.2 on 2026-10-09 04:25

import django.db.models.deletion
from django.db import migrations, models


# Actualizo los nombres físicos de columnas al formato minúsculo de PostgreSQL.
class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0003_remove_rol_id_rol_id_rol_alter_rol_nombre'),
        ('usuarios', '0003_usuario_debe_cambiar_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='especialidad',
            field=models.CharField(blank=True, db_column='especialidad', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='usuario',
            field=models.OneToOneField(db_column='idusuario', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='docente', serialize=False, to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='codigo_estudiante',
            field=models.CharField(blank=True, db_column='codigoestudiante', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='contacto_emergencia',
            field=models.CharField(blank=True, db_column='contactoemergencia', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, db_column='fechanacimiento', null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='telefono_emergencia',
            field=models.CharField(blank=True, db_column='telefonoemergencia', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='usuario',
            field=models.OneToOneField(db_column='idusuario', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='estudiante', serialize=False, to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ap_mat',
            field=models.CharField(db_column='apmat', max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ap_pat',
            field=models.CharField(db_column='appat', max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ci',
            field=models.CharField(blank=True, db_column='ci', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(db_column='correo', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='debe_cambiar_password',
            field=models.BooleanField(db_column='debe_cambiar_password', default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.BooleanField(db_column='estado', default=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, db_column='fecharegistro'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario',
            field=models.AutoField(db_column='idusuario', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombres',
            field=models.CharField(db_column='nombres', max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password_hash',
            field=models.CharField(db_column='passwordhash', max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(db_column='idrol', on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='rol.rol'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, db_column='telefono', max_length=30, null=True),
        ),
    ]
